### ISSUE TITLE
Request of Training Code

### ISSUE THREAD

**Issue by WWWWWLI** [csun22/LibriVoc-Dataset#1]
Thank you for the dataset, do you have any plans to make the training code public? Thank you.

**Comment by csun22** [comment]
Our collaborator holds the code by a privacy policy. So far, I don't know a scheduled timeline for publishing the training code. It might be this year's Fall.

**Comment by csun22** [comment]
Thank you for your reply. Unfortunately, our collaborator holds the code by a privacy policy. So far, I don't know a scheduled timeline for publishing the training code. It might be this year's Fall, but not promised.
